version: '3.8'

services:
  create-laravel:
    image: composer:2
    working_dir: /app
    volumes:
      - ./src:/app
    command: >
      sh -c "if [ -z \"\$(ls -A)\" ]; then
      echo 'src folder is empty -> installing Laravel 11...';
      composer create-project laravel/laravel . \"^11.0\"; 
      else 
      echo 'src folder is not empty -> skipping.'; 
      fi"
    restart: 'no'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo_app
    volumes:
      - ./src:/var/www/html
    ports:
      - "8000:80"
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/html/public
    depends_on:
      - create-laravel
      - db
    networks:
      - laravel

  db:
    image: mysql:8
    container_name: todo_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - laravel

  node:
    image: node:18
    container_name: todo_node
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
      - node_modules:/var/www/html/node_modules
    command: bash -c "npm install && tail -f /dev/null"
    depends_on:
      - create-laravel
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: todo_phpmyadmin
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: laravel
      PMA_PASSWORD: laravel
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  dbdata:
  node_modules: